extends Node

signal starmode(mode)
signal fadeset(dim)
signal lightset(light)
signal starheatset(temp,light)
signal envset(s,a,d)
signal duston(s)
signal froston()
signal flipin()
signal flipout()
signal flipload()
signal flipcomplete()
signal campaign_complete()
signal show_equipselect()
signal show_menu_armory()
signal button_generate_pressed()
signal button_mash(s)
signal build_alert(s)
signal zoom_map()
signal show_map()
signal show_new_map()
signal set_results(r,m)
signal show_results(r)
signal hide_results()
signal logout()
signal user_login(userid)
signal setup_items(id)
signal zone_hover_in(obj,s)
signal zone_hover_out()
signal load_draft(fd)
signal clear_prizes()
signal show_draft_buy(id,pos,s,n,c)
signal close_draft_buy()
signal draft_buy(price,item)
signal draft_error(s)
signal draft_bought()
signal dragging(sprite_texture, button_id, item_id)
signal drag_swap(button_id, s)
signal drag_swap_b(button_id, current_id)

signal clear_build_layer()
signal show_item_stats(p,n,e,m,s)
signal hide_item_stats()
signal show_menu_item_stats(p,o)
signal hide_menu_item_stats()
signal show_menu_options()
signal hide_menu_options()
signal ui_energy(n)
signal ui_metal(n)
signal ui_supply(n)
signal menu_button_press(menu_id)
signal submenu_button_press(menu_id)
signal unequip_buttons()
signal equip_buttons()
signal setup_armory_items(id)
signal setup_prize_slots()
signal sell_all()
signal show_sell_button()

signal new_build_spot(id,v,prices,radius,nametext,shieldradius)
signal cancel_build()
signal equip(bag)
signal do_move(id,type,s,posx,posy)
signal build_line(s,c)
signal build_spot_ghost(s)

signal mission_hover_in(pos)
signal mission_hover_out()
signal zone_click(zone_name,zone_desc,zone_id)

var current_menu_selected:String